#!/bin/bash
# implements deck aggregation algorithm described at:
# http://www.channelfireball.com/articles/magic-math-a-new-way-to-determine-an-aggregate-deck-list-rg-dragons/
#

if [[ $# == 0 || "$*" == *--help* ]]; then
	echo "Usage: ${0##*/} [decklist ...]

    Creates an aggregate list of cards from <decklist>s.
" >&2
fi

normalize_list() {
	awk '
		$1 ~ /[0-9]+x?/ {
			count = $1
			sub(/x$/, "", count)

			$1 = ""
			sub(/^ */, "")

			for (i=0; i<count-1; i++) {
				print substr($0, index($0, $2))
			}
		}
		/./ {print}
	' "$1" | sort
}

for decklist in "$@"; do
	declare -i count
	count=0
	oldcard=""
	while read card; do
		if [[ "$card" == "$oldcard" ]]; then
			((count++))
		else
			count=1
		fi

		echo "${count}th $card"

		oldcard="$card"
	done < <(normalize_list "$decklist")
done | sort | uniq -c | sort -rn | awk '
	{
		$1 = $1 / '$#' " " $1
		gsub(/^ */, "")
		print
	}
'

